name       : haskell-doctemplates
version    : 0.1.0.2
release    : 1
source     :
    - https://hackage.haskell.org/package/doctemplates-0.1.0.2/doctemplates-0.1.0.2.tar.gz : b752f52350daaa9bcf261a1f1af5852f75572093c3d0cdeb4822282fb3a18a6b
license    : BSD-3-Clause
component  : programming.haskell
summary    : This is the templating system used by pandoc.
description: |
    This is the templating system used by pandoc. It was formerly be a module in pandoc. It has been split off to make it easier to use independently.
builddeps  :
    - haskell-aeson
    - haskell-blaze-html
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
