name       : haskell-doctemplates
version    : 0.2.2.1
release    : 2
source     :
    - https://hackage.haskell.org/package/doctemplates-0.2.2.1/doctemplates-0.2.2.1.tar.gz : 6b0cfb565fc7fa90d71ac56b83aedecf670678e6f1441278877fbf399e9bccbf
license    : BSD-3-Clause
component  : programming.haskell
summary    : This is the templating system used by pandoc.
description: |
    This is the templating system used by pandoc. It was formerly be a module in pandoc. It has been split off to make it easier to use independently.
builddeps  :
    - haskell-aeson
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-parsec
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
